### ISSUE TITLE
Implement event log for authentication

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#10]
### Description

Components that send log requests must be authenticated.

### Tasks

- [x] Implement authentication event log for login event
- [x] Implement authentication event log for logout
- [x] Implement authentication event log for refresh
- [x] Implement authentication event log for failed authentication
- [x] Implement authentication event log for token exchange
- [x] Add unit tests 
- [x] Refactor the helper/service class
- [x] Add additional fields ipadress, timetodelete
- [x] Remove sessionid field
- [x] Update unit tests

### Acceptance Criteria

- [ ] Authentication is implemented
- [ ] An event is logged for login 
- [ ] An event is logged for logout 
- [ ] An event is logged for refresh event
- [ ] An event is logged for failed authentication
- [ ] An event is logged for token exchange
