### ISSUE TITLE
Setup Actions for build, sonar cloud analysis

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#11]
### Description

Setup actions to build, run unit tests and analyze audit log component

### Tasks

- [x] Setup build and run unit test action
- [ ] Setup sonar cloud analysis

### Acceptance Criteria

- [ ] Build and run unit test is triggered on every new PR
- [ ] Sonar cloud analysis is run on every PR
