### ISSUE TITLE
PostgresSql Update for Auditlog - Migration Plan

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#133]
### Description
Currently we use Timescaledb for partitioning in auditlog. We have enabled the TimescaleDb extension in Azure postgressql. Azure still do not support version upgrades when these extensions are enabled. Therefore, we need to migrate data, disable the extension and upgrade to the new postgres version. This migration can be tedious & time consuming with each upgrade when we need to handle millions of data. 
We need to find a better solution to handle this problem. We have 2 options

1. Keep using the timescaledb by designing a migration plan each time on version upgrade
2. Stop using the timescaledb. Come up with a migration plan for existing data and start using postgressql features for partitioning(this is quite a big work)

### Decision
To avoid repeated migrations during major version upgrades (as azure postgres does not support any of the partition extensions with major version upgrades), we will start using the native postgres partitioning. With native partitioning, automatic partitions will not be created. Therefore we will test out the use of background service in .net to create paritions automatically. The service will run once in a day and create partitions for past, current and next months if they do not exist.
The existing data will be migrated to a new table without timescale by the platform team. A issue is linked in the sub issue here. The platform team will migrate the data, remove the timescale extension and then upgrade the database to major version according to their upgrade plan.

```[tasklist]
### Tasks
- [x] Test the background service in auth audit log container app to create partitions on postgressql
- [x] Add script to create table eventlogv1 with range partition
- [x] Switch the log tabel from eventlog to eventlogv1
```
