### ISSUE TITLE
Implement K6 tests for audit log component

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#14]
### Description

Setup and implement K6 tests for api endpoints

### Tasks

- [x] Setup K6 tests
- [x] Implement test for authentication event endpoint
- [x] Implement test for authorization event endpoint

### Acceptance Criteria

- [x] K6 test is setup for auditlog component
- [x] Test cases implemented for authentication event
- [x] Test cases implemented for authorization event
