### ISSUE TITLE
Implement Hashing and signing for log

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#18]
### Description

Hashing of a selected set of properties together with signing the hash reduces the chance that logs have been tampered with.
https://learn.microsoft.com/en-us/dotnet/standard/security/cryptographic-signatures

Use SHA384 to Hash values.

Use RSA to sign HASH.

Do we need to support rotation of certificates. How should we know which certificates to

###Analysis

- [ ] Analyze and find out what are the list of values that need to be included in Hash.

### Tasks

- [ ]  Implement Hashing service
- [ ] Add hash, signature and reference to certificate/key fields in database
- [ ] Update function to store the new fields in database

### Acceptance Criteria

- [ ] Hashing is implemented
