### ISSUE TITLE
Create queue and  function projects to receive log requests from authentication/authorization

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#19]
### Description

We need queue to receive all event log requests and function to process the requests in the queue. When authentication/authorization sends log request, it will be sent to the log queue. Azure function will then process each item in the queue and send log request to the authentication/authorization end point 

### Tasks

- [x] Setup storage queue for event logging 
- [x] Setup function project to process events
- [x] Test the logging queue workflow from authentication component

### Acceptance Criteria

- [x] Queue is setup
- [x] Queue accepts log requests
- [x] Functions is set up
- [x] Function is able to process the log requests
