### ISSUE TITLE
Build Audit Log component

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-auth-audit-log#2]
### Description

The security log component will be the component responsible for adding logs to database for authorization and authentication events. 

### Architecture Recommendation

![Image](https://github.com/Altinn/altinn-auth-audit-log/assets/34273718/62fd5fd0-4e59-4249-8ff6-b2492d2c9712)

- Queue Storage for high-performance logging. (no need for waiting for db write)
- Azure Function to process the events in the Queue storage
- Auditlog component to process and store the events in the database
    - An api exposed via azure container app
    - Less hassle with container app setup and easy maintenance compared to kubernetes cluster 
- A postgres database to store the authentication and authorization events
- A separate table for authentication event
- A separate table for authorization event
- Write only for application user

### Security

- How to protect access to the event queue? 
    The assumption is that we share SAS key for storage queue with the authentication and authorization component and don't need any additional measures to protect the queue.

- **Hashing and signing**
Hashing of a selected set of properties together with signing the hash reduces the chance that logs have been tampered with. 
https://learn.microsoft.com/en-us/dotnet/standard/security/cryptographic-signatures
Use SHA384 to Hash values. 
The list of values that need to be included in Hash is
**TODO**

- Use RSA to sign HASH.
- Do we need to support rotation of certificates? 

### Database
We will use postgres database for authentication and authorization event logging. 

**Open Questions**
- Do we need a separate database server for auditlog? 

**Database structure for authentication events**
- Time - DateTime for when event happened. Set by producer of logevent
- UserId - The userId for the specific
- SupplierID - Supplier ID if relevant
- EventType - LoggedIn, FailedLogIn, LogOut
- Orgnumber
- AuthenticationMethod    
- AuthenticationLevel

**Database structure for authorization events**
For authorization Events, the following events is identified :

**PDP AuthorizationRequest** 
This is when some component requests the PDP to decide if a user/system is authorized 

The suggested approach is to store separate 

- subjectuserid
    The userid for the user requested
- subjectparty
    If relevant
- resourcepartyid
    The partyId for resource owner. If relevant. 
- resource
    Main resource Id (app, external resource +)
- instanceid
    InstanceId if relevation
- operation
    (read, write ++)
- TimeToDelete 
    Value when log should be deleted. Do we need it?
- IpAdress
    The Ipd address for the calling party. Up to 
- Decision
    The whole ContextRequest. This can be used to provide details about the resource 

```json
{
  "Request": {
    "ReturnPolicyIdList": true,
    "AccessSubject": [
      {
        "Attribute": [
          {
            "AttributeId": "urn:altinn:userid",
            "Value": "1"
          },
         {
            "AttributeId": "urn:altinn:role",
            "Value": "dagl"
          },
         {
            "AttributeId": "urn:altinn:role",
            "Value": "utinn"
          }
        ]
      }
    ],
    "Action": [
      {
        "Attribute": [
          {
            "AttributeId": "urn:oasis:names:tc:xacml:1.0:action:action-id",
            "Value": "read",
            "DataType": "http://www.w3.org/2001/XMLSchema#string"
          }
        ]
      }
    ],
    "Resource": [
      {
        "Attribute": [
          {
            "AttributeId": "urn:altinn:instance-id",
            "Value": "1000/26133fb5-a9f2-45d4-90b1-f6d93ad40713",
            "IncludeInResult": true
          },
          {
            "AttributeId": "urn:altinn:org",
            "Value": "skd"
          },
          {
            "AttributeId": "urn:altinn:app",
            "Value": "taxreport"
          },
          {
            "AttributeId": "urn:altinn:partyid",
            "Value": "1000"
            
          },
          {
            "AttributeId": "urn:altinn:task",
            "Value": "formfilling"
           
          }

        ]
      }
    ]
  }
}
```

#### Partitioning of table
We should test partitioning on the table so we do not need to do what we do in Altinn 2, where we rename the table every year.

https://severalnines.com/blog/guide-partitioning-data-postgresql/#:~:text=The%20maximum%20table%20size%20allowed,a%20hundredth%20of%20that%20space.

#### When to not log?

Should we log a request/response if we have cached it? (we currently do not cache decisions)

#### Data Expectations

50.000.000 instances
50 authorizations per instance
1kb per log

2.500.000.000 log lines 

2.500.000 MBytes 

2.5 Terra Bytes log

```[tasklist]
### Development Tasks
- [x] Setup new GIT repository for audit log
- [ ] #7
- [ ] #19
- [ ] #10
- [ ] https://github.com/Altinn/altinn-authorization/issues/461
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/40
- [ ] https://github.com/Altinn/altinn-authentication/issues/345
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/43
```

```[tasklist]
### Legal
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/4
```

```[tasklist]
### Infrastructure
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/24
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/27
- [ ] https://github.com/Altinn/altinn-authentication/issues/372
```

```[tasklist]
### Security
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/18
- [ ] Create a tool for simple recreation of hash and validation of the signature
```

```[tasklist]
### CI/CD
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/23
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/28
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/11
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/50
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/51
```

```[tasklist]
### Test Automation
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/14
- [ ] #72
```

```[tasklist]
### Performance
- [ ] https://github.com/Altinn/altinn-authorization/issues/554
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/17
```

```[tasklist]
### QA
- [x] Review the authentication event log data in at environment with the team members
- [x] Review the authorization event log data in at environment with the team members
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/46
```

```[tasklist]
### Documentation
- [ ] https://github.com/Altinn/altinn-auth-audit-log/issues/49
```

### Acceptance Criteria
- [x] Authentication events are stored in the database
- [x] Authorization events are stored in the database

**Comment by annerisbakk** [comment]
@acn-dgopa rydder i epicen og lukker den

**Comment by annerisbakk** [comment]
@acn-dgopa Lukker denne.
