### ISSUE TITLE
Setup github package registry for auditlog

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#23]
### Description

The auditlog component will be deployed as container app in azure. The code will be packaged as a package in github container registry. 

### Tasks

- [x] Setup workflow to build and package the auditlog component

### Acceptance Criteria

- [x] Github package registry is setup for auditlog component
- [x] Auditlog component is packaged as github package
- [x] The package is tagged with github commit sha as the tag identificator
