### ISSUE TITLE
Setup devtest environment for audit logging

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#24]
### Description

Infrastructure to host the audit-log component, storage queue for the log events, function to process the queue must be tested in a development/testing environment to ensure the log workflow/dataflow from authentication/authorization components. The infrastructure can be set up in test subscription with own resource group for audit-log component. 

### Tasks

- [x]  Setup container app for audit-log component
- [x] Setup storage queue to receive log events
- [x] Setup function app to process the events
- [x] Setup network access such that the access is granted to queue log request for calls from authentication/authorization component in platform cluster
- [x] Grant function app access to the queue (service principal?)
- [x] Grant function app access to the audit-log api (internal access?)

### Acceptance Criteria

- [x] A test environment is established for the audit-log component
- [x] A test queue is provisioned
- [x] A function app for testing is provisioned
- [x] Authentication/Authorization component in one of the test environment is able to queue event for logging
- [x] The function app is able to process the event queue and send log request to audit log component
- [x] The audit-log component is able tor receive log requests and event is logged to database
