### ISSUE TITLE
Infrastructure for auth-audit-log component

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#27]
### Description

Audit log component will be hosted as a container app. Authentication/Authorization component will write each authentication/authorization event to a storage queue. A function app is set with queue trigger such that each event is processed by the function app. The function app then sends api request to specific endpoint(Authentication/authorization) in auth-audit-log component. The auth-audit-log component write the event to the auth-audit-log database.

![Image](https://github.com/Altinn/altinn-auth-audit-log/assets/34273718/720d5cbd-7fab-4ff0-a4f4-54af723543c7)

### Tasks

- [x] Set up a resource group for audit log application (All the new resources below will be created in this resource group)
- [x] Setup Storage Queue
- [x] Setup function app
- [x] Setup auth-audit-log as container app
- [x] Setup ny postgres sql server? 
- [x] Setup network/domain configuration for connections between function app and container app
- [x] Setup security/network such that authentication component in platform gets access to the storage queue
- [x] Setup security/network such that function app gets access to the storage queue
- [x]  Setup security/network such that container app gets access to the postgres sql server

### Acceptance Criteria

- [x] New resource group is created
- [x] Storage Queue is setup
- [x] Function app is setup
- [x] auth-audit-log container app is setup
- [x] postgres sql server is setup
- [x] network/domain is setup for container app
- [x] network is configured for storage queue
- [x] network is configured for funciton app
- [x] network is configured for postgres sqls erver

**Comment by simon-ellefsen** [comment]
Support for container app secrets are currently limited in the Terraform provider. Temporary fix is to refer to the secret value instead of secret reference. Should be changed when provider support is added.
https://github.com/hashicorp/terraform-provider-azurerm/pull/23958

**Comment by acn-dgopa** [comment]
@simon-ellefsen I have now run the basic tests on the setup and it works as expected
