### ISSUE TITLE
Setup build/deploy GitHub action for audit log function application

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#28]
### Description

Function app changes must be continuously built and deployed to azure. The process must be implemented as a GitHub action.

### Tasks

- [x] Create a build action to build the function app on a pull request
- [x] Implement sonar scanner for the function app
- [x] Create deploy action to deploy the function app

### Acceptance Criteria

- [x] A deploy pipeline is created for function app
