### ISSUE TITLE
Modify Eventlog based on QA comments

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#40]
### Description

QA of the logging in at environment was taken as input for the discussion with the team about logging and the team came up with many good feedback points such as

- Use lookup tables for authentication type, authentication method, authentication level which can save the cost
- Use session id for a login session
- Remove column timetodelete, sanering script can calculate it from the createddatetime
- Should Refresh/Authentication implementation in <<app-lib-dotnet>> project must be optimized? Looks like too many calls are made

### Tasks

- [x] Remove the identifier column
- [x] Remove the timetodelete column
- [x] Add sessionid as guid/string column (Sessionid implementation will be a separate task)
- [x] Add lookup table for authentication event type
- [x] Add lookup table for authenticationmethod
- [x] Add lookup table for authenticationlevel
- [x] Update the authentication model
- [x] Update create table, functions script for authentication event log
- [x] Update repository class for the new db structure
- [x] Update the authentication component for mapping to match the new db structure
- [x] Update unit tests
- [ ] Update K6 tests

### Acceptance Criteria

- [ ] Db structure is updated
- [ ] Authentication component is updated
- [ ] Audit  log database has the following new tables
    - [ ] AuthenticationEventType table
    - [ ] AuthenticationMethod table
    - [ ] AuthenticationLevel table
- [ ] authentication.eventlog has the following columns
    - [ ] sessionid
    - [ ] created
    - [ ] userid
    - [ ] supplierid
    - [ ] orgnumber
    - [ ] isauthenticated
    - [ ] eventype (a number which should be looke up to AuthenticationEventType table)
    - [ ] authenticationmethod (a number which should be looke up to AuthenticationMethod table)
    - [ ] authenticationlevel (a number which should be looke up to AuthenticationLevel table)
    - [ ] ipaddress
