### ISSUE TITLE
Authorization event log - Iteration 2

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#43]
### Description

Following feedback is registered after the QA of the event log in authorization

- Introduce lookup tables for decision
- Remove identity field
- Include sessionid column
- Remove timetodelete

### Tasks

- [x] Introduce lookup tables for resource, operation, decision
- [x] Update database script
- [x]  Remove identity field
- [x] Include sessionid column
- [x] Remove timetodelete column
- [x] Update authorization event model
- [x] Add enumeration classes for decision?
- [x] Add k6 tests for auditlog component
- [x] Update unit tests

### Acceptance Criteria

- [x] New columns are added to the eventlog table in auhtorization schema
- [x] Authorization component logs the necessary information for authorization event
