### ISSUE TITLE
Add additional columns in audit log database

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#48]
### Description

It was agreed during the logging discussion that we implement session id to get overview of the user's activities for a given period of time. In addition the external session id, the token issuer and subscription key that was used to send api request is also logged in to the authentication event database

### Tasks

- [x] Add sessionid column
- [x] Add externalsessionid column
- [x] Add subscriptionkey column
- [x] Add externaltokenissuer column
- [x] update authenticationeventrepository class
- [x] Update model
- [x] Update db script for table and procedure

### Acceptance Criteria

- [ ] Additional columns sessionid, externalsessionid, subscriptionkey, externaltokenissuer are added
- [ ] data is saved in the additional columns
