### ISSUE TITLE
Authentication log

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-auth-audit-log#5]
### Description

As part of transistion to the new cloud platform we need to create a new Authentication log.

- Logtype. (login, failedlogin, logout)
- UserId/systemid/
- Timestamp
- Method
- Ip-address
- Sessionid 
- Supplier/System id  
- AdditionalInfo (possible needed in some fail scenarios?)

### Additional Information

- It should be possible to search logs and join them with other metadata like instance history

Do we need to log additional info like scope?

Docs
https://www.datatilsynet.no/rettigheter-og-plikter/virksomhetenes-plikter/informasjonssikkerhet-internkontroll/etablere-internkontroll/iverksette-styringssystem-for-informasjonssikkerhet/

https://www.digdir.no/digital-samhandling/veileder-identifikasjon-og-sporbarhet-i-elektronisk-kommunikasjon-med-og-i-offentlig-sektor/2992

#### Log requirements

As part of the requirements, we need to define

- How long can we store these logs
- Is there a difference in storage time for the different data
- Is there need for additional integrity on logs(hash++)

@benedicteos 

#### Log architecture

- What kind of log database should we use
- Should we use queue technology to improve speed and 

Suggestion

1. New TTPLog schema/db
2. Table for AuthenticationEvent 
3. New TTPLog component
4. Queue Storage for high-performance logging. (no need for waiting for db write
5. Azure Function for looking at log model and calling correct endppoo
6. Write only for application user

![image](https://user-images.githubusercontent.com/13309071/214868432-ed7de2f8-c40e-4881-8fd8-ca5760174d72.png)

### Tasks
- [ ] Define Log architecture

### Acceptance Criteria

- [ ] Logs every request where user logs direct in to Altinn 3 with OIDC
- [ ] Logs when Altinn 3 logins based on Altinn 2 session
- [ ] Logs when maskinporten token is exchanged
- [ ] Logs when id-porten token is exchanged
- [ ] Logs when logging out
- [ ] The logs should support at least 500.000.000 log inserts
- [ ] The log storage should not allow
