### ISSUE TITLE
Setup Release process for TT02/Prod

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#51]
### Description
A release routine must be setup to  deploy updates to TT02/Prod environment. As of now, the release routine for Team Authorisasjon is TT02 on tuesdays and prod on wednesdays.
A github package registry will be created for TT02 on every tuesday.  The package will have a release version in the format v[year].[revision] f.ex v2023.1 which means 1st release in year 2023.
The code will be tested for stability in TT02 for a week. The same package is then deployed to production.

### Tasks
- [x] Setup action to create a release version in TT02
- [x] Setup an action to deploy to specific environment
- [ ] Setup an action to create draft release

### Acceptance Criteria

- [x] A release routine is setup using github actions
