### ISSUE TITLE
Update readme to the auditlog project

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#63]
### Description

Add a readme file to the auditlog component that describes about the project and the practical guidelines.

### Tasks

- [ ] Update the readme with the project architecture and description
- [ ] Update the readme with getting started section

### Acceptance Criteria

- [ ] Readme is updated
- [ ] Development setup is available in the gettting started section
