### ISSUE TITLE
Setup database, repository project and core project for auditlog component

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#7]
### Description

The security log component will be the component responsible for adding logs to database for authorization and authentication.  Setup a database for audit log with  table AuthenticationEvent 

### Tasks

- [ ] Setup Yuniql for automated database scripts
- [ ] Add database script to create table AuthenticationEvent
- [ ] Add script to create function to write to authenticationevent table
- [ ] Add script to create function to read from authenticationevent table
- [ ] Create Core project that will establish services to integrate with  repository project
- [ ] Create Repository project that will establish services to read/write to the table
- [ ] Update AuthenticationEventcontroller post method to call core service
- [ ] Update AuthenticationEventController get method to call core service

### Acceptance Criteria

- [ ] A database with 2 tables are created
- [ ] Core project is created
- [ ] Repository project is created
- [ ] It is possible to create an authentication event via api endpoint
