### ISSUE TITLE
Establish a GET endpoint in auditlog api to retreive logs based on a user id, party id, organisation and date

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#77]
### Description

Currently we have some K6 tests in auditlog api app that can be run after deploy in any environment. The auditlog api will have access limited only to function app that processes the authentication and authorization events. So instead of  running several independent test suites against auditlog api and function app, it is a good idea to create end-to-end tests f.ex 

1. The test will start at a point where the bruno tests will add a queue message to the Queue storage
2. The new message in the queue storage will trigger the function app
3. The function app will process it and store in the database.

Now to verify that the end-to-end test, we have to assert the queue message against data in the database. This can be acheived by either running some db script (needs some access setting) to fetch the data from database or via a get endpoint that can retreive the log based on userid,partyid,organisationid or date. The latter if established can also be used by the service desk team to verify some data in connection to any service desk cases.

### Tasks

- [ ] Establish a GET method in authentication log api with scope authorization
    - [ ] Filters : userid, orgid, partyid, date 
- [ ] Establih a GET method in authorization log api with scope authorization
    - [ ] Filters : userid, orgid, partyid, date 

### Acceptance Criteria

- [ ] A new endpoint is established
- [ ] Possible to filter data by userid, orgid, partyid, date
