### ISSUE TITLE
Feedback on eventlog in tt02

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#80]
### Feedback after reviweing eventlog in tt02

@lovoll used some time to go over the logs and give some valuable feedback on eventlog.  the following feedback is received

1. På Autentisering er det noen innslag som ikke sier så mye bare tidspunkt ikke noen bruker og trolig heller ikke noen Autentiseringsmetode regner med at 0 er deafault for TokenExchange og AltinnPin henger ikke sammen.
2. Ser ut som SubjectPartyId ikke alltid får verdi selv om SubjectOrgnumber og SubjectOrgCode men det er kanskje ikke tilgjengelig uten ekstra oppslag.
3. Burde Resource vært mer entydig slik den er nå så ser det ut som den bare inneholder appid og ikke org og den sier vel heller ikke hvilken type resurs det er. App/ResourceRegister
4. Tenker vi må lage noen spørringer som kan trekke ut svar på standard spørsmål.
5. Tenker det blir bedre når sessionid for verdi i Autorisasjonsloggen.
6. Kunne vært lurt om Authentication Method og AuthenticationLevel hadde null når verdien manglet nå mistenker jeg at den blir 0 som sammenfaller med en autentisk verdi.
7. Mye bra her vi kan vel pusse litt på denne etter hvert som vi ser mangler.

```[tasklist]
### Tasks
- [x] Remove event logging for token exchange from altinn studio
- [ ] Find out if default authentication level and authentication method can be set to null when its null
- [ ] Create queries for the Standard questions we get from servicedesk
- [ ] Check if subjectpartyid can be enriched with partyid when orgcode/orgnumber is present in subject
```
