### ISSUE TITLE
Update release-deploy process

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#89]
### Description
A release routine must be setup to  deploy updates to TT02/Prod environment. As of now, the release routine for Team Authorisasjon is TT02 on tuesdays and prod on wednesdays.

**Container Application**
A github release will be created every wednesday at 00:00. The release will have a naming format [year].[month].[day]. A github package registry will be tagged on every wednesday for container app.  The package will have a release version in the format [year].[month].[day] f.ex 2024.3.18. The package will be deployed to TT02 on wednesday and production deploy will wait until next tuesday.
The code will be tested for stability in TT02 for a week. The same package is then deployed to production.

**Function application**
A github release will be created every tuesday at 00:00. The release will have a naming format [year].[month].[day]. f.ex 2024.3.18. The function app will be deployed to TT02 on wednesday and production deploy will wait until next tuesday.

### Tasks
- [x] Setup action to schedule a release, tag image and release notes draft with version format as [year].[month].[day]
- [x] Setup action to deploy to tt02 after a release
- [x] Update action to deploy to prod after tt02 deploy

### Acceptance Criteria

- [x] Release is created on every wednesday
- [x] Deploy fails when the container app is unhealthy after deploy
- [ ] Deploy fails when the function app is unhealthy after deploy
- [x] Deploy awaits approval on TT02 and prod
