### ISSUE TITLE
Create endpoint for authorizationevent log

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#9]
### Description

The security log component will be the component responsible for adding logs to database for authorization events. Add an endpoint to enable this logging.

### Tasks

- [x] Add authorizationevent controller for logging authorization events
- [x] Add function in postgres sql
- [x] Add service class
- [x] Add repository class
- [x] Add unit tests

### Acceptance Criteria

- [x] Endpoint for authorizationevent log is created

**Comment by annerisbakk** [comment]
Venter med testing til vi har miljø oppe
