### ISSUE TITLE
Publish release notes for the first version of auditlog

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#94]
### Description
Now the auditlog is ready to be deployed in production. Release notes draft will be created at 00:00 20.march. Publish the release notes and that will trigger the deployment to tt02 and production

### Tasks
- [x] Publish release notes
- [x] Update the deploy template for the weekly deployment to include auditlog

### Acceptance Criteria

- [x] Release notes is published
- [x] Deployed auditlog successfully to yt01, tt02, prod
- [x] Feature toggle for auditlog is turned on in all AT environments
- [x] Feature toggle for auditlog is turned on in TT02
- [x] Feature toggle for auditlog is turned on in Prod
